# Generated by Django 5.2.1 on 2025-05-16 05:46

from django.db import migrations, models
from datetime import date


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='year_discovered',
        ),
        migrations.AddField(
            model_name='artifact',
            name='date_found',
            field=models.DateField(default=date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artifact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artifact_images/'),
        ),
    ]
