# Generated by Django 5.2.1 on 2025-05-16 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_remove_artifact_year_discovered_artifact_date_found_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='date_found',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
