# Generated by Django 5.2.1 on 2025-05-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0003_alter_artifact_date_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artifacts/'),
        ),
    ]
