# Generated by Django 5.2.1 on 2025-05-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0004_artifact_qr_code_alter_artifact_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='qr_code',
        ),
    ]
