# Generated by Django 5.2.1 on 2025-05-16 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0005_remove_artifact_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('museum', 'Museum'), ('storage', 'Storage'), ('on_loan', 'On Loan')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_condition', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifacts.artifact')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artifacts.location')),
            ],
        ),
        migrations.CreateModel(
            name='RestorationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restoration_date', models.DateField()),
                ('description', models.TextField()),
                ('restored_by', models.CharField(blank=True, max_length=100, null=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifacts.artifact')),
            ],
        ),
    ]
