# Generated by Django 5.2.1 on 2025-05-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0006_location_artifactinventory_restorationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactinventory',
            name='condition',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artifactinventory',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
