# Generated by Django 5.2.1 on 2025-05-16 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0007_artifactinventory_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifactinventory',
            name='current_condition',
        ),
        migrations.AlterField(
            model_name='artifactinventory',
            name='artifact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='artifacts.artifact'),
        ),
        migrations.AlterField(
            model_name='restorationhistory',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restorations', to='artifacts.artifact'),
        ),
    ]
